DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friendships CASCADE;
DROP TABLE IF EXISTS puzzles CASCADE;
CREATE TABLE users  ( id SERIAL PRIMARY KEY NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, rating INTEGER NOT NULL );
CREATE TABLE friendships ( id SERIAL PRIMARY KEY NOT NULL, senderId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, recieverId INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE );
CREATE TABLE puzzles ( id SERIAL PRIMARY KEY NOT NULL, puzzle_type VARCHAR(255) NOT NULL, date_created VARCHAR(255) NOT NULL, puzzle TEXT NOT NULL, answer_key TEXT NOT NULL );