const sudoku = require('sudoku');

//creates a puzzle with its solution
const generatePuzzle = function () {
  const temp = sudoku.makepuzzle();
  const tempSolution = sudoku.solvepuzzle(temp);
  const pzzl = change0To9(temp);
  const pzzlSolution = change0To9(tempSolution);
  

  return { 
    puzzle: pzzl,
    solution: pzzlSolution
  }
}

//checks the solution
const sudokuSolutionCheck = function(submission, answer) {
  
  if (submission.length !== answer.length) {
    return false;
  }
  for( let i = 0; i < answer.length; i++) {
    if(submission[i] !== answer[i]) {
      return false;
    }
  }
  return true;
}
console.log(generatePuzzle())
module.exports = { generatePuzzle, sudokuSolutionCheck };

//changes the 0s to 9s when a puzzle is generated by sudoku
const change0To9 = function(sudoku) {
  let output = [];
  for (let num of sudoku) {
    if (num === 0) {
      output.push(9);
    } else {
      output.push(num);
    }
  }
  return output;
}