// change the 0s to 9s when a puzzle is generated by sudoku
const formatGuess = function(puzz, answers) {
  let output = [];
  for(let i = 0; i < puzz.length; i++) {
    const string = 'box-'+(i+1);
    if(answers[string]) {
      output.push(parseInt(answers[string]));
    } else {
      output.push(puzz[i]);
    }
  }
  // console.log(output);

  return output;
};

// check if a solution is correct
const sudokuSolutionCheck = function(submission, answer) {
  if (submission.length !== answer.length) {
    return false;
  }
  for( let i = 0; i < answer.length; i++) {
    if(submission[i] !== answer[i]) {
      return false;
    }
  }

  return true;
};

// check user answer
const checkAnswer = function(puzz,answers, key) {
  const guess = formatGuess(puzz,answers);
  const isRight = sudokuSolutionCheck(guess,key);

  // --- un-comment for testing ---
  // console.log('guess', guess);
  // console.log('key', key);
  
  if (isRight){
    console.log('correct');
    return true;
  } else {
    return false;
  }
};

module.exports = checkAnswer;
